version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos25
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - TZ=Asia/Shanghai
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=identityKey
      - NACOS_AUTH_IDENTITY_VALUE=identityValue
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    networks:
      - my-network
    command: --appendonly yes  --requirepass '123456'
networks:
  my-network:
    name: my-network
    external: true