version: '3.8'
services:
  mysql8:
    image: mysql:8.4.4
    container_name: mysql84
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/dongliyang/docker/mysql/datadir8:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=tiger
      - MYSQL_USER=tiger
      - MYSQL_PASSWORD=123456
    networks:
      - my-network
networks:
  my-network:
    name: my-network
    external: true