version: '3.8'
services:
  redis:
    image: redis:6.2.17
    container_name: redis6
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - my-network
    command: --appendonly yes  --requirepass '123456'
networks:
  my-network:
    name: my-network
    external: true